CREATE TABLE PasswordResets
(
    ResetID INT IDENTITY(1,1) PRIMARY KEY,
    Account_ID INT NOT NULL FOREIGN KEY REFERENCES USER_TABLE(Account_ID),
    ResetToken NVARCHAR(256) NOT NULL,
    ExpirationDate DATETIME NOT NULL,
    IsUsed BIT NOT NULL DEFAULT 0,
    IPAddress NVARCHAR(45) NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);

